name: adapter-build

on:
  push:
    branches:
      - '**'
  # pull_request:
  #   branches:
  #     - '**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        adapter:
          [
            'auto',
            'node',
            'cloudflare',
            'netlify_edge',
            'netlify_node',
            'vercel_edge',
            'vercel_severless'
          ]
    name: adapter-build-${{ matrix.adapter }}-test

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Adapter build
        run: ADAPTER=${{ matrix.adapter }} npx vite build
